services:
  api:
    image: stoinksapi:latest
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "3000:3000"

  frontend:
    image: stoinksfrontend:latest
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

  adminfrontend:
    image: stoinksadminfrontend:latest
    build:
      context: ./admin_frontend
    ports:
      - "5174:5173"
    depends_on:
      - api